services:
  gym-tracker:
    build: ./frontend
    container_name: gym-tracker-frontend
    restart: unless-stopped
    networks:
      - home_server

  gym-tracker-backend:
    build: ./backend
    container_name: gym-tracker-backend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    networks:
      - home_server

networks:
  home_server:
    external: true
